name: smart_expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cloud_firestore: ^6.7.1
  cloud_functions: ^6.3.5
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  firebase_storage: ^13.4.5
  flutter:
    sdk: flutter
  google_sign_in: 6.3.0
  http: ^1.6.0
  image_picker: ^1.2.3
  pdf: ^3.13.0
  printing: ^5.15.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
